service: intervieweeBankService

provider:
  name: aws
  runtime: nodejs8.10

functions:
  listAccounts:
    handler: handler.listAccounts
    environment:
      MONGODB_URI: ${env:MONGODB_URI}
    events:
      - http:
          method: get
          path: v1/accounts
          private: false
  createAccount:
    environment:
      MONGODB_URI: ${env:MONGODB_URI}
    handler: handler.insertAccount
    events:
      - http:
          method: post
          path: v1/accounts
          private: false
  listTransactions:
    handler: handler.listTransactions
    environment:
      MONGODB_URI: ${env:MONGODB_URI}
    events:
      - http:
          method: get
          path: v1/transactions
          private: false
  createTransaction:
    environment:
      MONGODB_URI: ${env:MONGODB_URI}
      SQS_URL: ${env:SQS_URL}
    handler: handler.insertTransaction
    events:
      - sqs: ${env:SQS_ARN}
      - http:
          method: post
          path: v1/transactions
          private: false