service: intervieweeBankService

provider:
  name: aws
  runtime: nodejs8.10

functions:
  listTransactions:
    handler: handler.listTransactions
    events:
      - http:
          method: get
          path: transactions
          private: false
  createAccount:
    environment:
      MONGODB_URI: ${env:MONGODB_URI}
    handler: handler.insertAccount
    events:
      - http:
          method: post
          path: v1/accounts
          private: false
  createTransaction:
    environment:
      MONGODB_URI: ${env:MONGODB_URI}
    handler: handler.insertTransaction
    events:
      - http:
          method: post
          path: v1/transactions
          private: false