service: intervieweeBankService

custom:
  queueName: "Gini-test-categorisation"

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource:
        Fn::GetAtt: [ SQSQueue, Arn ]

functions:
  listAccounts:
    handler: handler.listAccounts
    environment:
      MONGODB_URI: ${env:MONGODB_URI}
    events:
      - http:
          method: get
          path: v1/accounts
          private: false
  createAccount:
    environment:
      MONGODB_URI: ${env:MONGODB_URI}
    handler: handler.insertAccount
    events:
      - http:
          method: post
          path: v1/accounts
          private: false
  listTransactions:
    handler: handler.listTransactions
    environment:
      MONGODB_URI: ${env:MONGODB_URI}
    events:
      - http:
          method: get
          path: v1/transactions
          private: false
  createTransaction:
    environment:
      MONGODB_URI: ${env:MONGODB_URI}
      SQS_URL:
        Ref: SQSQueue
    handler: handler.insertTransaction
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ SQSQueue, Arn ]
      - http:
          method: post
          path: v1/transactions
          private: false

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueName}
