service: senecaService

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

functions:
  createAccount:
    handler: handler.insertStudyEventOfCourseSession
    events:
      - http:
          method: post
          path: api/v1/course/{courseId}
          private: false

